### ISSUE TITLE
patch_petalinux does not work for Petalinux tools 2024.1

### ISSUE THREAD

**Issue by idheepan** [fdmysterious/petalinux-docker#1]
There is no `function accept_license` in the new installer. Instead, it is just a block of code from line 240 to 276. 

As a workaround, I have modified the patch_petalinux.sh script to

```bash
perl -i -ne 'print unless $. >= 240 && $. <= 276' "$1"
```

**Comment by fdmysterious** [comment]
Hi, thanks for your suggestion. After a quick read, it seems that they added the `-y` option to the installer script that automatically accepts the license agreement. No more `patch_petalinux.sh` script needed :)

I am testing this right now, and will create a new `2024.1` when I will have ensured the environment builds correctly.

**Comment by fdmysterious** [comment]
New installation scripts are available in the `2024.1` branch. Thank you! :)
